
"""
Convolutional Autoencoder + Snapshot Attention + Trajectory Encoder (GRU) for ALSFRS-slope regression

This script is adapted from your classification architecture (autoencoder + snapshot attention + longitudinal GRU)
to predict a continuous outcome: ALSFRS-slope.

Key features:
- Subject-level K-fold CV (no leakage across timepoints)
- Dual-objective training: reconstruction (regularizer) + regression
- Two predictive branches:
    (A) Snapshot branch: order-invariant attention over timepoint latents
    (B) Trajectory branch: order-aware GRU over latent sequence (0h -> 6h -> 24h)
  fused via concatenation and an MLP regressor

Outputs:
- best model checkpoint per fold (selected by lowest validation RMSE)
- per-subject predictions (train/val) saved to CSV
- per-subject snapshot & trajectory attention weights saved to CSV

Assumptions about input:
- Spectral "images" are stored as Excel files in directories: out_0h/, out_6h/, out_24h/
- Files are named: <code>.xlsx (where code is from ALSFRS.csv)
- ALSFRS.csv contains columns: code, ALSFRS-slope (and optionally Group)

Tested use-case:
- 20 ALS subjects with ALSFRS-slope labels (small-n regime)

Author: generated by ChatGPT based on user's prior script.
"""

import os
import argparse
from typing import List, Tuple, Optional, Dict

import numpy as np
import pandas as pd
from openpyxl import load_workbook

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


# -----------------------------
# Reproducibility
# -----------------------------
def set_seeds(seed: int = 42) -> None:
    torch.manual_seed(seed)
    np.random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


# -----------------------------
# Dataset
# -----------------------------
class ExcelImageDatasetRegression(Dataset):
    """
    Loads 3 timepoints per subject (0h, 6h, 24h) as a tensor: (T=3, C=1, H, W)
    and returns a float target y (ALSFRS-slope) plus the subject code.

    NOTE: This keeps the per-sample min-max normalization used in your original script.
    If absolute intensity is biologically meaningful, consider moving to dataset-level scaling.
    """
    def __init__(self, codes: List[str], targets: List[float], timepoint_dirs: List[str]):
        self.codes = [str(c) for c in codes]
        self.targets = [float(y) for y in targets]
        self.timepoint_dirs = timepoint_dirs

    def __len__(self) -> int:
        return len(self.codes)

    @staticmethod
    def load_excel_as_image(filepath: str) -> np.ndarray:
        wb = load_workbook(filepath, data_only=True)
        ws = wb.active

        data = []
        for row_idx, row in enumerate(ws.iter_rows(values_only=True)):
            if row_idx == 0:
                continue  # skip header row
            row_data = []
            for col_idx, cell in enumerate(row):
                if col_idx == 0:
                    continue  # skip emission label column
                if isinstance(cell, (int, float)) and cell is not None:
                    row_data.append(float(cell))
                else:
                    row_data.append(0.0)
            if len(row_data) > 0:
                data.append(row_data)

        img = np.array(data, dtype=np.float32)
        if img.size == 0:
            raise ValueError(f"No valid numeric data in {filepath}")

        # per-sample min-max normalization
        mn, mx = float(img.min()), float(img.max())
        if mx > mn:
            img = (img - mn) / (mx - mn)
        else:
            img = np.zeros_like(img, dtype=np.float32)

        return img

    def __getitem__(self, idx: int):
        code = self.codes[idx]
        y = self.targets[idx]

        tp_imgs = []
        for tp_dir in self.timepoint_dirs:
            fp = os.path.join(tp_dir, f"{code}.xlsx")
            arr = self.load_excel_as_image(fp)
            if arr.ndim == 2:
                arr = arr[np.newaxis, :, :]  # (1, H, W)
            tp_imgs.append(torch.tensor(arr, dtype=torch.float32))

        images = torch.stack(tp_imgs, dim=0)  # (T, C, H, W)
        target = torch.tensor(y, dtype=torch.float32)
        return images, target, code


# -----------------------------
# Model components
# -----------------------------
class ConvEncoder(nn.Module):
    def __init__(self, in_channels: int, latent_dim: int):
        super().__init__()
        self.conv1 = nn.Sequential(
            nn.Conv2d(in_channels, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
        )
        self.conv2 = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
        )
        self.conv3 = nn.Sequential(
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
        )
        self.conv4 = nn.Sequential(
            nn.Conv2d(128, 256, kernel_size=3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(),
        )

        self.flatten_size = None
        self.fc = None
        self.latent_dim = latent_dim
        self.encoded_shape = None
        self.input_shape = None

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if self.input_shape is None:
            self.input_shape = (x.shape[2], x.shape[3])

        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)

        if self.encoded_shape is None:
            self.encoded_shape = (x.shape[1], x.shape[2], x.shape[3])

        if self.fc is None:
            self.flatten_size = x.shape[1] * x.shape[2] * x.shape[3]
            self.fc = nn.Linear(self.flatten_size, self.latent_dim).to(x.device)

        x = x.view(x.size(0), -1)
        z = self.fc(x)
        return z


class ConvDecoder(nn.Module):
    def __init__(self, latent_dim: int, out_channels: int, encoded_shape: Tuple[int, int, int], target_shape: Tuple[int, int]):
        super().__init__()
        enc_c, enc_h, enc_w = encoded_shape
        tgt_h, tgt_w = target_shape
        self.enc_c, self.enc_h, self.enc_w = enc_c, enc_h, enc_w
        self.tgt_h, self.tgt_w = tgt_h, tgt_w

        self.fc = nn.Linear(latent_dim, enc_c * enc_h * enc_w)

        self.deconv1 = nn.Sequential(
            nn.ConvTranspose2d(256, 128, kernel_size=3, stride=2, padding=1, output_padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
        )
        self.deconv2 = nn.Sequential(
            nn.ConvTranspose2d(128, 64, kernel_size=3, stride=2, padding=1, output_padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
        )
        self.deconv3 = nn.Sequential(
            nn.ConvTranspose2d(64, 32, kernel_size=3, stride=2, padding=1, output_padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
        )
        self.final_conv = nn.Conv2d(32, out_channels, kernel_size=3, padding=1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, z: torch.Tensor) -> torch.Tensor:
        x = self.fc(z)
        x = x.view(x.size(0), self.enc_c, self.enc_h, self.enc_w)
        x = self.deconv1(x)
        x = self.deconv2(x)
        x = self.deconv3(x)
        x = self.final_conv(x)

        if x.shape[2] != self.tgt_h or x.shape[3] != self.tgt_w:
            x = torch.nn.functional.interpolate(
                x, size=(self.tgt_h, self.tgt_w), mode="bilinear", align_corners=False
            )

        return self.sigmoid(x)


class AttentionAggregation(nn.Module):
    """Order-invariant attention over timepoint latent vectors."""
    def __init__(self, latent_dim: int):
        super().__init__()
        self.attention_net = nn.Sequential(
            nn.Linear(latent_dim, 64),
            nn.Tanh(),
            nn.Linear(64, 1),
        )

    def forward(self, latent_vectors: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        # latent_vectors: (batch, T, latent_dim)
        scores = self.attention_net(latent_vectors).squeeze(-1)      # (batch, T)
        weights = torch.softmax(scores, dim=1)                       # (batch, T)
        z_agg = torch.sum(latent_vectors * weights.unsqueeze(-1), dim=1)  # (batch, latent_dim)
        return z_agg, weights


class TemporalEvolutionEncoder(nn.Module):
    """Order-aware GRU over time-ordered latent vectors, with optional step-attention."""
    def __init__(self, input_dim: int, hidden_dim: int = 64, use_step_attention: bool = True):
        super().__init__()
        self.rnn = nn.GRU(input_size=input_dim, hidden_size=hidden_dim, batch_first=True)
        self.use_step_attention = use_step_attention
        self.step_attn = nn.Linear(hidden_dim, 1) if use_step_attention else None

    def forward(self, latent_seq: torch.Tensor) -> Tuple[torch.Tensor, Optional[torch.Tensor]]:
        out, h = self.rnn(latent_seq)  # out: (batch, T, hidden_dim)
        if not self.use_step_attention:
            return h[-1], None
        scores = self.step_attn(out).squeeze(-1)     # (batch, T)
        weights = torch.softmax(scores, dim=1)       # (batch, T)
        embed = torch.sum(out * weights.unsqueeze(-1), dim=1)  # (batch, hidden_dim)
        return embed, weights


class RegressorHead(nn.Module):
    def __init__(self, in_dim: int, dropout: float = 0.3):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, 128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, 1),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x).squeeze(-1)  # (batch,)


class FusionRegressor(nn.Module):
    def __init__(self, snap_dim: int, traj_dim: int, dropout: float = 0.3):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(snap_dim + traj_dim, 128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, 1),
        )

    def forward(self, z_snap: torch.Tensor, z_traj: torch.Tensor) -> torch.Tensor:
        return self.net(torch.cat([z_snap, z_traj], dim=1)).squeeze(-1)


class ConvAutoencoderSnapshotsTrajectoryRegression(nn.Module):
    """
    Outputs:
        reconstructions: (batch, T, C, H, W)
        y_fused:         (batch,)
        snap_weights:    (batch, T)
        traj_weights:    (batch, T) or None
        y_snap:          (batch,)   auxiliary snapshot-only prediction
        y_traj:          (batch,)   auxiliary trajectory-only prediction
    """
    def __init__(self, in_channels: int, latent_dim: int, traj_hidden_dim: int = 64):
        super().__init__()
        self.encoder = ConvEncoder(in_channels, latent_dim)
        self.attention = AttentionAggregation(latent_dim)
        self.temporal = TemporalEvolutionEncoder(latent_dim, traj_hidden_dim, use_step_attention=True)

        self.decoder = None

        self.snap_head = RegressorHead(latent_dim)
        self.traj_head = RegressorHead(traj_hidden_dim)
        self.fusion_head = FusionRegressor(latent_dim, traj_hidden_dim)

        self.in_channels = in_channels
        self.latent_dim = latent_dim
        self.traj_hidden_dim = traj_hidden_dim

    def forward(self, timepoint_images: torch.Tensor):
        # timepoint_images: (batch, T, C, H, W)
        batch, T = timepoint_images.shape[0], timepoint_images.shape[1]

        latents = []
        for t in range(T):
            latents.append(self.encoder(timepoint_images[:, t]))  # (batch, latent_dim)
        latent_seq = torch.stack(latents, dim=1)  # (batch, T, latent_dim)

        # init decoder once shapes are known
        if self.decoder is None and self.encoder.encoded_shape is not None:
            self.decoder = ConvDecoder(
                self.latent_dim,
                self.in_channels,
                self.encoder.encoded_shape,
                self.encoder.input_shape,
            ).to(timepoint_images.device)

        # snapshot embedding
        z_snap, snap_w = self.attention(latent_seq)

        # trajectory embedding
        z_traj, traj_w = self.temporal(latent_seq)

        # reconstructions per timepoint
        recon = torch.stack([self.decoder(latent_seq[:, t]) for t in range(T)], dim=1)

        # predictions
        y_snap = self.snap_head(z_snap)
        y_traj = self.traj_head(z_traj)
        y_fused = self.fusion_head(z_snap, z_traj)

        return recon, y_fused, snap_w, traj_w, y_snap, y_traj


# -----------------------------
# Metrics
# -----------------------------
def safe_pearsonr(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)
    if y_true.size < 2:
        return float("nan")
    if np.std(y_true) == 0 or np.std(y_pred) == 0:
        return float("nan")
    return float(np.corrcoef(y_true, y_pred)[0, 1])


def compute_regression_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> Dict[str, float]:
    rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
    mae = float(mean_absolute_error(y_true, y_pred))
    r2 = float(r2_score(y_true, y_pred)) if len(np.unique(y_true)) > 1 else float("nan")
    r = safe_pearsonr(y_true, y_pred)
    return {"rmse": rmse, "mae": mae, "r2": r2, "pearson_r": r}


# -----------------------------
# Train / Validate / Collect
# -----------------------------
def train_epoch(model, loader, optimizer, device, alpha: float, beta: float, gamma: float, huber_delta: float, y_mean: float, y_std: float):
    model.train()
    recon_crit = nn.MSELoss()
    # robust regression loss (Huber)
    reg_crit = nn.SmoothL1Loss(beta=huber_delta)

    total_loss = total_recon = total_fused = total_aux = 0.0
    y_true_all, y_pred_all = [], []

    for images, y, _codes in loader:
        images = images.to(device)
        y = y.to(device)

        # standardize target within fold (optional, but enabled here)
        y_norm = (y - y_mean) / (y_std + 1e-8)

        optimizer.zero_grad()
        recon, y_fused, snap_w, traj_w, y_snap, y_traj = model(images)

        # losses on normalized targets
        recon_loss = recon_crit(recon, images)
        fused_loss = reg_crit(y_fused, y_norm)

        snap_loss = reg_crit(y_snap, y_norm)
        traj_loss = reg_crit(y_traj, y_norm)
        aux_loss = 0.5 * (snap_loss + traj_loss)

        loss = alpha * recon_loss + beta * fused_loss + gamma * aux_loss
        loss.backward()
        optimizer.step()

        total_loss += float(loss.item())
        total_recon += float(recon_loss.item())
        total_fused += float(fused_loss.item())
        total_aux += float(aux_loss.item())

        # store predictions in original scale for reporting
        y_pred = (y_fused.detach().cpu().numpy() * (y_std + 1e-8)) + y_mean
        y_true = y.detach().cpu().numpy()
        y_true_all.append(y_true)
        y_pred_all.append(y_pred)

    y_true_all = np.concatenate(y_true_all) if y_true_all else np.array([])
    y_pred_all = np.concatenate(y_pred_all) if y_pred_all else np.array([])
    metrics = compute_regression_metrics(y_true_all, y_pred_all) if y_true_all.size else {"rmse": np.nan, "mae": np.nan, "r2": np.nan, "pearson_r": np.nan}

    n = max(1, len(loader))
    return (total_loss / n, total_recon / n, total_fused / n, total_aux / n, metrics)


def validate(model, loader, device, alpha: float, beta: float, gamma: float, huber_delta: float, y_mean: float, y_std: float):
    model.eval()
    recon_crit = nn.MSELoss()
    reg_crit = nn.SmoothL1Loss(beta=huber_delta)

    total_loss = total_recon = total_fused = total_aux = 0.0
    y_true_all, y_pred_all = [], []
    snap_all, traj_all = [], []

    with torch.no_grad():
        for images, y, _codes in loader:
            images = images.to(device)
            y = y.to(device)
            y_norm = (y - y_mean) / (y_std + 1e-8)

            recon, y_fused, snap_w, traj_w, y_snap, y_traj = model(images)

            recon_loss = recon_crit(recon, images)
            fused_loss = reg_crit(y_fused, y_norm)
            snap_loss = reg_crit(y_snap, y_norm)
            traj_loss = reg_crit(y_traj, y_norm)
            aux_loss = 0.5 * (snap_loss + traj_loss)

            loss = alpha * recon_loss + beta * fused_loss + gamma * aux_loss

            total_loss += float(loss.item())
            total_recon += float(recon_loss.item())
            total_fused += float(fused_loss.item())
            total_aux += float(aux_loss.item())

            y_pred = (y_fused.detach().cpu().numpy() * (y_std + 1e-8)) + y_mean
            y_true = y.detach().cpu().numpy()
            y_true_all.append(y_true)
            y_pred_all.append(y_pred)

            if snap_w is not None:
                snap_all.append(snap_w.detach().cpu().numpy())
            if traj_w is not None:
                traj_all.append(traj_w.detach().cpu().numpy())

    y_true_all = np.concatenate(y_true_all) if y_true_all else np.array([])
    y_pred_all = np.concatenate(y_pred_all) if y_pred_all else np.array([])
    metrics = compute_regression_metrics(y_true_all, y_pred_all) if y_true_all.size else {"rmse": np.nan, "mae": np.nan, "r2": np.nan, "pearson_r": np.nan}

    snap_arr = np.concatenate(snap_all) if len(snap_all) else None
    traj_arr = np.concatenate(traj_all) if len(traj_all) else None

    n = max(1, len(loader))
    return (total_loss / n, total_recon / n, total_fused / n, total_aux / n, metrics, snap_arr, traj_arr)


def collect_reports(model, loader, device, fold: int, split: str, y_mean: float, y_std: float):
    model.eval()
    rows = []

    with torch.no_grad():
        for images, y, codes in loader:
            images = images.to(device)
            y = y.to(device)

            recon, y_fused_norm, snap_w, traj_w, y_snap_norm, y_traj_norm = model(images)

            # invert normalization to report in original scale
            y_fused = (y_fused_norm.detach().cpu().numpy() * (y_std + 1e-8)) + y_mean
            y_snap = (y_snap_norm.detach().cpu().numpy() * (y_std + 1e-8)) + y_mean
            y_traj = (y_traj_norm.detach().cpu().numpy() * (y_std + 1e-8)) + y_mean

            y_true = y.detach().cpu().numpy()
            snap_np = snap_w.detach().cpu().numpy() if snap_w is not None else None
            traj_np = traj_w.detach().cpu().numpy() if traj_w is not None else None

            for i, code in enumerate(codes):
                r = {
                    "fold": fold,
                    "split": split,
                    "code": str(code),
                    "y_true": float(y_true[i]),
                    "y_pred_fused": float(y_fused[i]),
                    "y_pred_snap": float(y_snap[i]),
                    "y_pred_traj": float(y_traj[i]),
                }
                if snap_np is not None and snap_np.shape[1] >= 3:
                    r.update({
                        "snap_w_0h": float(snap_np[i, 0]),
                        "snap_w_6h": float(snap_np[i, 1]),
                        "snap_w_24h": float(snap_np[i, 2]),
                    })
                else:
                    r.update({"snap_w_0h": np.nan, "snap_w_6h": np.nan, "snap_w_24h": np.nan})

                if traj_np is not None and traj_np.shape[1] >= 3:
                    r.update({
                        "traj_w_0h": float(traj_np[i, 0]),
                        "traj_w_6h": float(traj_np[i, 1]),
                        "traj_w_24h": float(traj_np[i, 2]),
                    })
                else:
                    r.update({"traj_w_0h": np.nan, "traj_w_6h": np.nan, "traj_w_24h": np.nan})

                rows.append(r)

    return pd.DataFrame(rows)


# -----------------------------
# Main
# -----------------------------
def parse_args():
    p = argparse.ArgumentParser(description="Predict ALSFRS-slope from SWCNT emission spectra (3 timepoints) using AE+attention+trajectory.")
    p.add_argument("--alsfrs_csv", default="ALSFRS.csv", help="CSV with columns code and ALSFRS-slope.")
    p.add_argument("--code_col", default="code", help="Column name for subject codes.")
    p.add_argument("--target_col", default="ALSFRS-slope", help="Column name for ALSFRS slope target.")
    p.add_argument("--group_col", default="Group", help="Optional group column; used only if you set --group_filter.")
    p.add_argument("--group_filter", default="ALS", help="If group_col exists, keep only rows where group_col == group_filter. Set to empty to disable.")
    p.add_argument("--timepoint_dirs", default="out_0h,out_6h,out_24h", help="Comma-separated directories for timepoints in chronological order.")
    p.add_argument("--outdir", default="alsfrs_regression_outputs", help="Output directory.")
    p.add_argument("--latent_dim", type=int, default=512, help="Latent dim from ConvEncoder.")
    p.add_argument("--traj_hidden_dim", type=int, default=64, help="GRU hidden dim for trajectory.")
    p.add_argument("--batch_size", type=int, default=4)
    p.add_argument("--epochs", type=int, default=200)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--weight_decay", type=float, default=0.0)
    p.add_argument("--alpha", type=float, default=1.0, help="Reconstruction loss weight.")
    p.add_argument("--beta", type=float, default=1.0, help="Fused regression loss weight.")
    p.add_argument("--gamma", type=float, default=0.2, help="Auxiliary regression loss weight (snapshot+traj).")
    p.add_argument("--huber_delta", type=float, default=1.0, help="Huber delta (SmoothL1 beta).")
    p.add_argument("--folds", type=int, default=5)
    p.add_argument("--patience", type=int, default=25, help="Early stopping patience (epochs) based on val RMSE.")
    p.add_argument("--seed", type=int, default=42)
    return p.parse_args()


def main():
    args = parse_args()
    set_seeds(args.seed)

    timepoint_dirs = [s.strip() for s in args.timepoint_dirs.split(",") if s.strip()]
    if len(timepoint_dirs) != 3:
        raise ValueError("Expected exactly 3 timepoint directories (e.g., out_0h,out_6h,out_24h).")

    os.makedirs(args.outdir, exist_ok=True)
    ckpt_dir = os.path.join(args.outdir, "checkpoints")
    os.makedirs(ckpt_dir, exist_ok=True)

    # device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # load ALSFRS labels
    df = pd.read_csv(args.alsfrs_csv)
    # handle possible leading spaces in columns
    df.columns = [c.strip() for c in df.columns]

    if args.group_filter and args.group_col.strip() in df.columns:
        df = df[df[args.group_col.strip()] == args.group_filter].copy()

    if args.code_col not in df.columns or args.target_col not in df.columns:
        raise ValueError(f"ALSFRS CSV must contain columns '{args.code_col}' and '{args.target_col}'. Found: {df.columns.tolist()}")

    df = df[[args.code_col, args.target_col]].copy()
    df = df.dropna(subset=[args.code_col, args.target_col])
    df[args.code_col] = df[args.code_col].astype(str)
    df[args.target_col] = pd.to_numeric(df[args.target_col], errors="coerce")
    df = df.dropna(subset=[args.target_col]).copy()

    # verify files exist for all timepoints; drop missing
    keep_rows = []
    missing = 0
    for _, row in df.iterrows():
        code = row[args.code_col]
        ok = True
        for tp in timepoint_dirs:
            fp = os.path.join(tp, f"{code}.xlsx")
            if not os.path.exists(fp):
                ok = False
                break
        if ok:
            keep_rows.append(row)
        else:
            missing += 1

    if missing > 0:
        print(f"WARNING: Dropped {missing} subjects from ALSFRS CSV because one or more timepoint .xlsx files were missing.")

    df = pd.DataFrame(keep_rows)
    if df.empty:
        raise RuntimeError("No subjects left after checking for required Excel files.")

    codes = df[args.code_col].values
    y = df[args.target_col].values.astype(np.float32)

    print(f"Loaded targets for {len(codes)} subjects.")
    print(f"ALSFRS-slope range: min={float(np.min(y)):.3f}, max={float(np.max(y)):.3f}")

    # CV
    kf = KFold(n_splits=args.folds, shuffle=True, random_state=args.seed)
    fold_summaries = []
    all_reports = []

    print("\n" + "=" * 70)
    print("STARTING SUBJECT-LEVEL CROSS-VALIDATION (REGRESSION)")
    print(f"Total subjects: {len(codes)}")
    print(f"Timepoints per subject: {len(timepoint_dirs)}")
    print(f"CV folds: {args.folds}")
    print("=" * 70)

    for fold, (train_idx, val_idx) in enumerate(kf.split(codes), start=1):
        print(f"\n{'='*70}\nFOLD {fold}/{args.folds}\n{'='*70}")

        train_codes, train_y = codes[train_idx], y[train_idx]
        val_codes, val_y = codes[val_idx], y[val_idx]

        # fold-level y normalization stats
        y_mean = float(np.mean(train_y))
        y_std = float(np.std(train_y) if np.std(train_y) > 0 else 1.0)

        print(f"Train subjects: {len(train_codes)} | Val subjects: {len(val_codes)}")
        print(f"Target standardization: mean={y_mean:.3f}, std={y_std:.3f} (train fold)")

        train_ds = ExcelImageDatasetRegression(train_codes.tolist(), train_y.tolist(), timepoint_dirs)
        val_ds = ExcelImageDatasetRegression(val_codes.tolist(), val_y.tolist(), timepoint_dirs)

        train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True)
        val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False)

        # infer input dims
        sample_images, _, _ = next(iter(train_loader))
        T, C, H, W = sample_images.shape[1], sample_images.shape[2], sample_images.shape[3], sample_images.shape[4]
        print(f"Data dimensions: T={T}, C={C}, H={H}, W={W}")

        model = ConvAutoencoderSnapshotsTrajectoryRegression(
            in_channels=C,
            latent_dim=args.latent_dim,
            traj_hidden_dim=args.traj_hidden_dim,
        ).to(device)

        total_params = sum(p.numel() for p in model.parameters())
        print(f"Model params: {total_params:,}")

        optimizer = optim.Adam(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)

        best_val_rmse = float("inf")
        best_epoch = -1
        best_path = os.path.join(ckpt_dir, f"best_model_fold{fold}.pth")

        patience_left = args.patience

        for epoch in range(1, args.epochs + 1):
            tr_loss, tr_recon, tr_fused, tr_aux, tr_metrics = train_epoch(
                model, train_loader, optimizer, device,
                alpha=args.alpha, beta=args.beta, gamma=args.gamma,
                huber_delta=args.huber_delta, y_mean=y_mean, y_std=y_std
            )
            va_loss, va_recon, va_fused, va_aux, va_metrics, snap_w, traj_w = validate(
                model, val_loader, device,
                alpha=args.alpha, beta=args.beta, gamma=args.gamma,
                huber_delta=args.huber_delta, y_mean=y_mean, y_std=y_std
            )

            # checkpoint by val RMSE
            if va_metrics["rmse"] < best_val_rmse - 1e-9:
                best_val_rmse = va_metrics["rmse"]
                best_epoch = epoch
                patience_left = args.patience
                torch.save({
                    "state_dict": model.state_dict(),
                    "y_mean": y_mean,
                    "y_std": y_std,
                    "args": vars(args),
                }, best_path)
            else:
                patience_left -= 1

            if epoch % 10 == 0 or epoch == 1:
                print(f"\nEpoch {epoch}/{args.epochs}")
                print(f"  Train: loss={tr_loss:.4f} recon={tr_recon:.4f} fused={tr_fused:.4f} aux={tr_aux:.4f} | RMSE={tr_metrics['rmse']:.3f} MAE={tr_metrics['mae']:.3f} R2={tr_metrics['r2']:.3f} r={tr_metrics['pearson_r']:.3f}")
                print(f"  Val  : loss={va_loss:.4f} recon={va_recon:.4f} fused={va_fused:.4f} aux={va_aux:.4f} | RMSE={va_metrics['rmse']:.3f} MAE={va_metrics['mae']:.3f} R2={va_metrics['r2']:.3f} r={va_metrics['pearson_r']:.3f}")

                if snap_w is not None and snap_w.shape[1] == 3:
                    print("  Snapshot attention (mean over val): "
                          f"0h={snap_w[:,0].mean():.3f}, 6h={snap_w[:,1].mean():.3f}, 24h={snap_w[:,2].mean():.3f}")
                if traj_w is not None and traj_w.shape[1] == 3:
                    print("  Trajectory step-attn (mean over val): "
                          f"0h={traj_w[:,0].mean():.3f}, 6h={traj_w[:,1].mean():.3f}, 24h={traj_w[:,2].mean():.3f}")

            if patience_left <= 0:
                print(f"\nEarly stopping triggered at epoch {epoch}. Best val RMSE={best_val_rmse:.3f} @ epoch {best_epoch}.")
                break

        # reload best and export reports
        ckpt = torch.load(best_path, map_location=device)
        model.load_state_dict(ckpt["state_dict"])
        model.to(device)

        # loaders for deterministic reports
        train_rep_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=False)
        val_rep_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False)

        df_train = collect_reports(model, train_rep_loader, device, fold=fold, split="train", y_mean=y_mean, y_std=y_std)
        df_val = collect_reports(model, val_rep_loader, device, fold=fold, split="val", y_mean=y_mean, y_std=y_std)
        df_fold = pd.concat([df_train, df_val], ignore_index=True)
        all_reports.append(df_fold)

        # fold metrics on VAL (best checkpoint)
        y_true_val = df_val["y_true"].values
        y_pred_val = df_val["y_pred_fused"].values
        fold_metrics = compute_regression_metrics(y_true_val, y_pred_val)
        fold_metrics["fold"] = fold
        fold_metrics["best_epoch"] = best_epoch
        fold_summaries.append(fold_metrics)

        print(f"\nFOLD {fold} COMPLETE")
        print(f"  Best epoch: {best_epoch}")
        print(f"  Val metrics (fused): RMSE={fold_metrics['rmse']:.3f} MAE={fold_metrics['mae']:.3f} R2={fold_metrics['r2']:.3f} r={fold_metrics['pearson_r']:.3f}")

    # save pooled reports
    df_all = pd.concat(all_reports, ignore_index=True)
    report_path = os.path.join(args.outdir, "alsfrs_predictions_and_attention_all_folds.csv")
    df_all.to_csv(report_path, index=False)

    # CV summary
    df_sum = pd.DataFrame(fold_summaries)
    sum_path = os.path.join(args.outdir, "cv_summary.csv")
    df_sum.to_csv(sum_path, index=False)

    # ------------------------------------------------------------------
    # Stability analysis (mirrors the classification script idea):
    # Use the held-out VAL subjects (each subject appears once across folds)
    # to summarize which timepoints/trajectory-steps are consistently weighted.
    # ------------------------------------------------------------------
    df_val_only = df_all[df_all["split"] == "val"].copy()
    if not df_val_only.empty:
        # ------------------------------------------------------------------
        # Per-subject held-out table (VAL only): predictions + errors
        # Each subject should appear exactly once across folds in df_val_only.
        # This table is useful for downstream plots and identifying influential cases.
        # ------------------------------------------------------------------
        df_holdout = df_val_only.copy()

        # Ensure numeric
        for col in ["y_true", "y_pred_fused", "y_pred_snap", "y_pred_traj"]:
            if col in df_holdout.columns:
                df_holdout[col] = pd.to_numeric(df_holdout[col], errors="coerce")

        # Fused head errors (primary)
        df_holdout["err_fused"] = df_holdout["y_pred_fused"] - df_holdout["y_true"]
        df_holdout["abs_err_fused"] = df_holdout["err_fused"].abs()
        df_holdout["sq_err_fused"] = df_holdout["err_fused"] ** 2

        # Optional: branch errors if present
        if "y_pred_snap" in df_holdout.columns:
            df_holdout["err_snap"] = df_holdout["y_pred_snap"] - df_holdout["y_true"]
            df_holdout["abs_err_snap"] = df_holdout["err_snap"].abs()
        if "y_pred_traj" in df_holdout.columns:
            df_holdout["err_traj"] = df_holdout["y_pred_traj"] - df_holdout["y_true"]
            df_holdout["abs_err_traj"] = df_holdout["err_traj"].abs()

        # Rank most influential (largest abs error on held-out set)
        df_holdout["abs_err_rank"] = df_holdout["abs_err_fused"].rank(ascending=False, method="min")
        top_k = int(min(5, df_holdout.shape[0]))
        df_holdout["is_top{}_abs_err".format(top_k)] = df_holdout["abs_err_rank"] <= top_k

        # Sort for convenience (worst errors first), but do not change fold assignments
        df_holdout_sorted = df_holdout.sort_values(["abs_err_fused", "fold"], ascending=[False, True]).copy()

        heldout_path = os.path.join(args.outdir, "heldout_predictions_errors.csv")
        df_holdout_sorted.to_csv(heldout_path, index=False)
        # Overall metrics on held-out subjects for each head
        overall_rows = []
        for head_name, pred_col in [("fused", "y_pred_fused"), ("snapshot_only", "y_pred_snap"), ("trajectory_only", "y_pred_traj")]:
            m = compute_regression_metrics(df_val_only["y_true"].values, df_val_only[pred_col].values)
            m["head"] = head_name
            overall_rows.append(m)
        df_overall = pd.DataFrame(overall_rows)
        overall_path = os.path.join(args.outdir, "overall_val_metrics_by_head.csv")
        df_overall.to_csv(overall_path, index=False)

        # Timepoint weight stability (mean per fold, then stability across folds)
        weight_cols = ["snap_w_0h", "snap_w_6h", "snap_w_24h", "traj_w_0h", "traj_w_6h", "traj_w_24h"]
        df_weights = df_val_only.copy()
        if df_weights[weight_cols].isna().all(axis=1).any():
            df_weights = df_weights[~df_weights[weight_cols].isna().all(axis=1)].copy()

        fold_means = df_weights.groupby("fold", as_index=False)[weight_cols].mean()
        fold_means_path = os.path.join(args.outdir, "timepoint_weights_mean_by_fold.csv")
        fold_means.to_csv(fold_means_path, index=False)

        stab_rows = []
        for c in weight_cols:
            stab_rows.append({
                "weight": c,
                "mean_over_subjects": float(df_weights[c].mean()),
                "std_over_subjects": float(df_weights[c].std(ddof=1)) if df_weights.shape[0] > 1 else 0.0,
                "mean_over_folds": float(fold_means[c].mean()) if fold_means.shape[0] > 0 else float("nan"),
                "std_over_folds": float(fold_means[c].std(ddof=1)) if fold_means.shape[0] > 1 else 0.0,
            })
        df_stab = pd.DataFrame(stab_rows)
        stab_path = os.path.join(args.outdir, "timepoint_weight_stability.csv")
        df_stab.to_csv(stab_path, index=False)

        # Correlate weights with ALSFRS slope and with absolute prediction error (fused head)
        # IMPORTANT: df_val_only may have a non-0..N-1 index (e.g., if it was filtered/concatenated).
        # Build abs_err as a Series indexed like df_val_only, then align by index when subsetting.
        corr_rows = []
        abs_err = np.abs(df_val_only["y_pred_fused"].values - df_val_only["y_true"].values)
        abs_err_s = pd.Series(abs_err, index=df_val_only.index)
        for c in weight_cols:
            s = df_weights[c]
            y = df_weights["y_true"]

            def safe_corr(a, b):
                a = np.asarray(a, dtype=float)
                b = np.asarray(b, dtype=float)
                m = np.isfinite(a) & np.isfinite(b)
                a = a[m]; b = b[m]
                if a.size < 3: return float("nan")
                if np.std(a) < 1e-12 or np.std(b) < 1e-12: return float("nan")
                return float(np.corrcoef(a, b)[0, 1])

            r_y = safe_corr(s.values, y.values)
            # Align errors to the same subjects/rows used for weights
            r_abs = safe_corr(s.values, abs_err_s.loc[df_weights.index].values)
            corr_rows.append({"weight": c, "pearson_r_with_y_true": r_y, "pearson_r_with_abs_error": r_abs})
        df_corr = pd.DataFrame(corr_rows)
        corr_path = os.path.join(args.outdir, "timepoint_weight_correlations.csv")
        df_corr.to_csv(corr_path, index=False)

        print("\n" + "-" * 70)
        print("STABILITY REPORT (held-out VAL subjects only)")
        print("-" * 70)
        print("Saved:")
        print(f"  {overall_path}")
        print(f"  {heldout_path}")
        print(f"  {fold_means_path}")
        print(f"  {stab_path}")
        print(f"  {corr_path}")

        try:
            df_stab2 = df_stab.dropna(subset=["mean_over_folds"]).copy()
            df_stab2["std_over_folds"] = df_stab2["std_over_folds"].fillna(0.0)
            print("\nTimepoint weights (mean_over_folds ± std_over_folds):")
            for _, rr in df_stab2.iterrows():
                print("  {}: {:.3f} ± {:.3f}".format(rr["weight"], rr["mean_over_folds"], rr["std_over_folds"]))
        except Exception:
            pass


    # pick the single "best" fold checkpoint (lowest val RMSE) and copy it to outdir
    if len(df_sum) and "rmse" in df_sum.columns:
        best_fold = int(df_sum.loc[df_sum["rmse"].idxmin(), "fold"])
        best_ckpt_src = os.path.join(ckpt_dir, f"best_model_fold{best_fold}.pth")
        best_ckpt_dst = os.path.join(args.outdir, "best_model_overall.pth")
        try:
            import shutil
            shutil.copy2(best_ckpt_src, best_ckpt_dst)
            print(f"Best overall checkpoint (lowest val RMSE) copied to: {best_ckpt_dst}")
        except Exception as e:
            print(f"WARNING: Could not copy best checkpoint: {e}")

    print("\n" + "=" * 70)
    print("CROSS-VALIDATION SUMMARY (VAL, fused head)")
    print("=" * 70)
    print(df_sum[["fold", "rmse", "mae", "r2", "pearson_r", "best_epoch"]].to_string(index=False))

    print("\nSaved:")
    print(f"  {report_path}")
    print(f"  {sum_path}")
    print(f"  checkpoints in: {ckpt_dir}")


if __name__ == "__main__":
    main()