#!/usr/bin/env python3
"""Struct-env smoke tests: ASE SWCNT generator, Open Babel, AmberTools nucleic
builder (tleap). Produces small artifacts used by docking smokes.
Writes results/smoke_tests/{ase_openbabel,nucleic_acid_builder}.json.
Run in stmn2-struct."""
import os, sys, subprocess, tempfile
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from lib_common import ROOT, write_json, utc_now
import lib_struct as ls

SMOKE = os.path.join(ROOT, "results", "smoke_tests")
ART = os.path.join(SMOKE, "_artifacts")
os.makedirs(ART, exist_ok=True)

def smoke_ase_openbabel():
    rec = {"test": "ase_openbabel", "utc": utc_now()}
    try:
        n, m = 7, 5
        tube = ls.build_tube(n, m, target_length_A=25.0)   # short test tube
        pos = tube.get_positions()
        measured_d = ls.measured_diameter(pos)
        geo = ls.tube_geometry(n, m)
        analytic_d, theta = geo["analytic_diameter_A"], geo["chiral_angle_deg"]
        pdb = os.path.join(ART, "swcnt_test_7_5.pdb")
        pdbqt = os.path.join(ART, "swcnt_test_7_5.pdbqt")
        ls.write_pdb(pos, pdb)
        ls.write_carbon_pdbqt(pos, pdbqt)            # controlled type A / charge 0
        typ = ls.validate_pdbqt_typing(pdbqt)
        # Open Babel tool-function check (independent format conversion)
        xyz = os.path.join(ART, "swcnt_test_7_5.xyz")
        ob = subprocess.run(["obabel", pdb, "-O", xyz], capture_output=True, text=True)
        rec.update({
            "passed": bool(abs(measured_d - analytic_d) < 0.5 and typ["all_type_A"]
                           and typ["all_charge_zero"] and ob.returncode == 0),
            "chirality": [n, m],
            "analytic_diameter_A": round(analytic_d, 3),
            "measured_diameter_A": round(measured_d, 3),
            "diameter_diff_A": round(abs(measured_d - analytic_d), 3),
            "chiral_angle_deg": round(theta, 3),
            "n_carbons_test_tube": len(tube),
            "pdbqt_typing": typ,
            "openbabel_returncode": ob.returncode,
        })
    except Exception as e:
        rec.update({"passed": False, "error": f"{type(e).__name__}: {e}"})
    write_json(os.path.join(SMOKE, "ase_openbabel.json"), rec)
    return rec

def smoke_nucleic_builder():
    rec = {"test": "nucleic_acid_builder", "builder": "AmberTools tleap (DNA.OL15)",
           "utc": utc_now()}
    try:
        seq = "GTGTGTGTGTGTGT"  # GT7
        res = []
        for i, b in enumerate(seq):
            name = {"A": "DA", "C": "DC", "G": "DG", "T": "DT"}[b]
            if i == 0: name += "5"
            elif i == len(seq) - 1: name += "3"
            res.append(name)
        pdb = os.path.join(ART, "gt7.pdb")
        with tempfile.NamedTemporaryFile("w", suffix=".in", delete=False) as tf:
            tf.write("source leaprc.DNA.OL15\n")
            tf.write("m = sequence { " + " ".join(res) + " }\n")
            tf.write(f"savepdb m {pdb}\n")
            tf.write("quit\n")
            leapin = tf.name
        p = subprocess.run(["tleap", "-f", leapin], capture_output=True, text=True)
        # verify residues, backbone atoms, no missing
        residues, atomnames = set(), set()
        with open(pdb) as fh:
            for line in fh:
                if line.startswith("ATOM"):
                    residues.add(line[22:26].strip())
                    atomnames.add(line[12:16].strip())
        backbone_required = {"P", "O5'", "C5'", "C4'", "C3'", "O3'"}
        has_backbone = backbone_required <= atomnames or {"O5'", "C5'", "C4'", "C3'"} <= atomnames
        rec.update({
            "passed": (len(residues) == 14 and has_backbone and "Errors = 0" in p.stdout),
            "n_residues": len(residues),
            "expected_residues": 14,
            "backbone_atoms_present": sorted(backbone_required & atomnames),
            "n_unique_atom_names": len(atomnames),
            "tleap_errors_zero": "Errors = 0" in p.stdout,
            "note": "single B/extended-form strand; conformer ensemble generated by "
                    "sander Langevin MD + cpptraj RMSD clustering (not RDKit/MMFF).",
        })
    except Exception as e:
        rec.update({"passed": False, "error": f"{type(e).__name__}: {e}"})
    write_json(os.path.join(SMOKE, "nucleic_acid_builder.json"), rec)
    return rec

def smoke_ligand_prep():
    """Rigid ssDNA ligand PDBQT via AmberTools mol2 -> controlled AutoDock typing.
    Documents that Meeko 0.5/0.7 fail on bare ssDNA (separately, in docking env)
    and that this controlled, current-tool route is used instead (not MGLTools)."""
    import lib_ligprep as lp
    rec = {"test": "ligand_prep", "route": "tleap mol2 -> controlled AutoDock rigid PDBQT",
           "utc": utc_now()}
    try:
        mol2 = os.path.join(ART, "gt7.mol2")
        pdbqt = os.path.join(ART, "gt7_rigid.pdbqt")
        ok, _ = lp.build_ssdna_mol2("GTGTGTGTGTGTGT", mol2, tmpdir=ART)
        info = lp.mol2_to_rigid_pdbqt(mol2, pdbqt)
        valid_ad = {"A", "C", "N", "NA", "OA", "P", "SA", "HD"}
        types_ok = set(info["ad_type_counts"]) <= valid_ad
        rec.update({
            "passed": bool(ok and info["torsdof"] == 0 and types_ok and info["n_written"] > 0),
            "tleap_mol2_built": ok,
            "n_heavy_preserved": info["n_heavy"],
            "n_atoms_written": info["n_written"],
            "nonpolar_H_merged": info["n_nonpolar_H_merged"],
            "torsdof": info["torsdof"],
            "ad_types": info["ad_type_counts"],
            "all_autodock_types_valid": types_ok,
            "meeko_note": "Meeko 0.5.0 (RDKit KeyError) and 0.7.1 (query-bond / gemmi) "
                          "both fail to prepare bare ssDNA in this env; documented "
                          "controlled route used instead. NOT MGLTools.",
        })
    except Exception as e:
        rec.update({"passed": False, "error": f"{type(e).__name__}: {e}"})
    write_json(os.path.join(SMOKE, "ligand_prep.json"), rec)
    return rec

if __name__ == "__main__":
    a = smoke_ase_openbabel(); print("ase_openbabel:", a.get("passed"),
        "d_meas", a.get("measured_diameter_A"), "d_analytic", a.get("analytic_diameter_A"))
    b = smoke_nucleic_builder(); print("nucleic_builder:", b.get("passed"),
        "residues", b.get("n_residues"))
    c = smoke_ligand_prep(); print("ligand_prep:", c.get("passed"),
        "heavy", c.get("n_heavy_preserved"), "TORSDOF", c.get("torsdof"))
